In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/uber_rides.csv")

print(df.shape)
df.head()

(160609, 29)

,datetime,Date,Time,year,month,day,weekday,hour,ride_date,Event,...,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23 12:29:38,2024-03-23,12:29:38,2024,3,23,Saturday,12,2024-03-23,Normal Day,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29 18:01:39,2024-11-29,18:01:39,2024,11,29,Friday,18,2024-11-29,Wedding_Season,...,14.0,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,NaN,NaN,UPI
2,2024-08-23 08:56:10,2024-08-23,08:56:10,2024,8,23,Friday,8,2024-08-23,Monsoon,...,25.8,NaN,NaN,NaN,NaN,NaN,NaN,4.9,4.9,Debit Card
3,2024-10-21 17:17:25,2024-10-21,17:17:25,2024,10,21,Monday,17,2024-10-21,Normal Day,...,28.5,NaN,NaN,NaN,NaN,NaN,NaN,4.6,5.0,UPI
4,2024-09-16 22:08:00,2024-09-16,22:08:00,2024,9,16,Monday,22,2024-09-16,Normal Day,...,19.6,NaN,NaN,NaN,NaN,NaN,NaN,4.1,4.3,UPI

In [4]:
df = df[
    df["Booking Status"].isin(
        [
            "Completed",
            "Cancelled by Customer",
            "Cancelled by Driver",
            "No Driver Found"
        ]
    )
]

df["is_cancelled"] = np.where(
    df["Booking Status"] == "Completed",
    0,
    1
)

df["is_cancelled"].value_counts()

is_cancelled
0    99666
1    51280
Name: count, dtype: int64

In [5]:
df["hour_of_day"] = df["hour"]

df[["hour", "hour_of_day"]].head()

   hour  hour_of_day
0    12           12
2     8            8
3    17           17
4    22           22
5     9            9

In [6]:
df[["Avg VTAT", "Avg CTAT"]].isnull().sum()

Avg VTAT    11207
Avg CTAT    51280
dtype: int64

In [7]:
df["Avg VTAT"] = df["Avg VTAT"].fillna(
    df["Avg VTAT"].median()
)

df["Avg CTAT"] = df["Avg CTAT"].fillna(
    df["Avg CTAT"].median()
)

In [8]:
df[["Avg VTAT", "Avg CTAT"]].isnull().sum()

Avg VTAT    0
Avg CTAT    0
dtype: int64

In [9]:
columns_to_drop = [
    "Booking Status",
    "Ride Distance",
    "Booking Value",
    "Driver Ratings",
    "Customer Rating",
    "Booking ID",
    "Customer ID",
    "Date",
    "Time"
]

df = df.drop(columns=columns_to_drop)

In [10]:
df.columns.tolist()

['datetime',
 'year',
 'month',
 'day',
 'weekday',
 'hour',
 'ride_date',
 'Event',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Payment Method',
 'is_cancelled',
 'hour_of_day']

In [11]:
print(df.shape)
print(df.columns.tolist())

(150946, 22)
['datetime', 'year', 'month', 'day', 'weekday', 'hour', 'ride_date', 'Event', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT', 'Cancelled Rides by Customer', 'Reason for cancelling by Customer', 'Cancelled Rides by Driver', 'Driver Cancellation Reason', 'Incomplete Rides', 'Incomplete Rides Reason', 'Payment Method', 'is_cancelled', 'hour_of_day']

In [12]:
columns_to_drop = [
    "Cancelled Rides by Customer",
    "Reason for cancelling by Customer",
    "Cancelled Rides by Driver",
    "Driver Cancellation Reason",
    "Incomplete Rides",
    "Incomplete Rides Reason"
]

df = df.drop(columns=columns_to_drop)

print(df.columns.tolist())

['datetime', 'year', 'month', 'day', 'weekday', 'hour', 'ride_date', 'Event', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT', 'Payment Method', 'is_cancelled', 'hour_of_day']

In [13]:
df.isnull().sum()

datetime               0
year                   0
month                  0
day                    0
weekday                0
hour                   0
ride_date              0
Event                  0
Vehicle Type           0
Pickup Location        0
Drop Location          0
Avg VTAT               0
Avg CTAT               0
Payment Method     51280
is_cancelled           0
hour_of_day            0
dtype: int64

In [14]:
df["Payment Method"] = df["Payment Method"].fillna("Unknown")

In [15]:
df.isnull().sum()

datetime           0
year               0
month              0
day                0
weekday            0
hour               0
ride_date          0
Event              0
Vehicle Type       0
Pickup Location    0
Drop Location      0
Avg VTAT           0
Avg CTAT           0
Payment Method     0
is_cancelled       0
hour_of_day        0
dtype: int64

In [16]:
df = df.drop(columns=["hour"])

In [17]:
df = df.drop(columns=["datetime", "ride_date"])

In [18]:
print(df.shape)

print(df.columns.tolist())

(150946, 13)
['year', 'month', 'day', 'weekday', 'Event', 'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT', 'Avg CTAT', 'Payment Method', 'is_cancelled', 'hour_of_day']

In [19]:
df.to_csv(
    "../data/clean_uber_rides_2024.csv",
    index=False
)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!